// Code generated by protoc-gen-go. DO NOT EDIT.
// source: add.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	add.proto

It has these top-level messages:
	SumReq
	SumResp
	ConcatReq
	ConcatResp
	HelloReq
	HelloResp
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The sum request contains two parameters.
type SumReq struct {
	A int64 `protobuf:"varint,1,opt,name=a" json:"a,omitempty"`
	B int64 `protobuf:"varint,2,opt,name=b" json:"b,omitempty"`
}

func (m *SumReq) Reset()                    { *m = SumReq{} }
func (m *SumReq) String() string            { return proto.CompactTextString(m) }
func (*SumReq) ProtoMessage()               {}
func (*SumReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SumReq) GetA() int64 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *SumReq) GetB() int64 {
	if m != nil {
		return m.B
	}
	return 0
}

// The sum response contains the result of the calculation.
type SumResp struct {
	V int64 `protobuf:"varint,1,opt,name=v" json:"v,omitempty"`
}

func (m *SumResp) Reset()                    { *m = SumResp{} }
func (m *SumResp) String() string            { return proto.CompactTextString(m) }
func (*SumResp) ProtoMessage()               {}
func (*SumResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SumResp) GetV() int64 {
	if m != nil {
		return m.V
	}
	return 0
}

// The Concat request contains two parameters.
type ConcatReq struct {
	A string `protobuf:"bytes,1,opt,name=a" json:"a,omitempty"`
	B string `protobuf:"bytes,2,opt,name=b" json:"b,omitempty"`
}

func (m *ConcatReq) Reset()                    { *m = ConcatReq{} }
func (m *ConcatReq) String() string            { return proto.CompactTextString(m) }
func (*ConcatReq) ProtoMessage()               {}
func (*ConcatReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ConcatReq) GetA() string {
	if m != nil {
		return m.A
	}
	return ""
}

func (m *ConcatReq) GetB() string {
	if m != nil {
		return m.B
	}
	return ""
}

// The Concat response contains the result of the concatenation.
type ConcatResp struct {
	V string `protobuf:"bytes,1,opt,name=v" json:"v,omitempty"`
}

func (m *ConcatResp) Reset()                    { *m = ConcatResp{} }
func (m *ConcatResp) String() string            { return proto.CompactTextString(m) }
func (*ConcatResp) ProtoMessage()               {}
func (*ConcatResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ConcatResp) GetV() string {
	if m != nil {
		return m.V
	}
	return ""
}

type HelloReq struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloReq) Reset()                    { *m = HelloReq{} }
func (m *HelloReq) String() string            { return proto.CompactTextString(m) }
func (*HelloReq) ProtoMessage()               {}
func (*HelloReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HelloReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResp struct {
	V string `protobuf:"bytes,1,opt,name=v" json:"v,omitempty"`
}

func (m *HelloResp) Reset()                    { *m = HelloResp{} }
func (m *HelloResp) String() string            { return proto.CompactTextString(m) }
func (*HelloResp) ProtoMessage()               {}
func (*HelloResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *HelloResp) GetV() string {
	if m != nil {
		return m.V
	}
	return ""
}

func init() {
	proto.RegisterType((*SumReq)(nil), "pb.SumReq")
	proto.RegisterType((*SumResp)(nil), "pb.SumResp")
	proto.RegisterType((*ConcatReq)(nil), "pb.ConcatReq")
	proto.RegisterType((*ConcatResp)(nil), "pb.ConcatResp")
	proto.RegisterType((*HelloReq)(nil), "pb.HelloReq")
	proto.RegisterType((*HelloResp)(nil), "pb.HelloResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Add service

type AddClient interface {
	// Sums two integers.
	Sum(ctx context.Context, in *SumReq, opts ...grpc.CallOption) (*SumResp, error)
	// Concatenates two strings
	Concat(ctx context.Context, in *ConcatReq, opts ...grpc.CallOption) (*ConcatResp, error)
}

type addClient struct {
	cc *grpc.ClientConn
}

func NewAddClient(cc *grpc.ClientConn) AddClient {
	return &addClient{cc}
}

func (c *addClient) Sum(ctx context.Context, in *SumReq, opts ...grpc.CallOption) (*SumResp, error) {
	out := new(SumResp)
	err := grpc.Invoke(ctx, "/pb.Add/Sum", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addClient) Concat(ctx context.Context, in *ConcatReq, opts ...grpc.CallOption) (*ConcatResp, error) {
	out := new(ConcatResp)
	err := grpc.Invoke(ctx, "/pb.Add/Concat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Add service

type AddServer interface {
	// Sums two integers.
	Sum(context.Context, *SumReq) (*SumResp, error)
	// Concatenates two strings
	Concat(context.Context, *ConcatReq) (*ConcatResp, error)
}

func RegisterAddServer(s *grpc.Server, srv AddServer) {
	s.RegisterService(&_Add_serviceDesc, srv)
}

func _Add_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Add/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServer).Sum(ctx, req.(*SumReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Add_Concat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConcatReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServer).Concat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Add/Concat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServer).Concat(ctx, req.(*ConcatReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Add_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Add",
	HandlerType: (*AddServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _Add_Sum_Handler,
		},
		{
			MethodName: "Concat",
			Handler:    _Add_Concat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "add.proto",
}

func init() { proto.RegisterFile("add.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xbb, 0xce, 0x82, 0x30,
	0x18, 0x86, 0xff, 0xc2, 0x1f, 0xb4, 0xaf, 0x87, 0xa1, 0x8b, 0xc8, 0x60, 0x48, 0x63, 0xa2, 0x2e,
	0x0c, 0x7a, 0x05, 0xc6, 0xc5, 0x19, 0xae, 0xa0, 0xb5, 0x6c, 0x40, 0xab, 0x1c, 0xae, 0xdf, 0x94,
	0x53, 0xc0, 0xed, 0x7b, 0xf3, 0x3e, 0x7d, 0xda, 0x7e, 0xa0, 0x42, 0xa9, 0xc8, 0x7c, 0x74, 0xa5,
	0x99, 0x63, 0x24, 0x3f, 0xc2, 0x4b, 0xea, 0x3c, 0x4e, 0xdf, 0x6c, 0x0d, 0x22, 0x7c, 0x12, 0x92,
	0xb3, 0x1b, 0x13, 0x61, 0x93, 0xf4, 0x9d, 0x2e, 0x49, 0xbe, 0xc3, 0xa2, 0xa5, 0x4a, 0x63, 0x8b,
	0x66, 0xc0, 0x1a, 0x7e, 0x02, 0x7d, 0xe8, 0xe2, 0x25, 0xaa, 0x99, 0x81, 0xce, 0x0c, 0xd4, 0x1a,
	0x02, 0x60, 0x00, 0xa7, 0x12, 0x6a, 0x25, 0x07, 0x2c, 0x9f, 0x69, 0x96, 0x69, 0xeb, 0x60, 0xf8,
	0x2f, 0x44, 0x9e, 0xf6, 0x65, 0x3b, 0xf3, 0x3d, 0x68, 0xdf, 0xff, 0x1e, 0xbd, 0xc6, 0x70, 0xef,
	0x4a, 0xb1, 0x10, 0x6e, 0x52, 0xe7, 0x0c, 0x91, 0x91, 0x51, 0xf7, 0x9d, 0x60, 0x35, 0xce, 0xa5,
	0xe1, 0x7f, 0xec, 0x02, 0xaf, 0xbb, 0x9f, 0x6d, 0x6c, 0x31, 0x3e, 0x3a, 0xd8, 0x4e, 0xa3, 0x45,
	0xa5, 0xd7, 0x6e, 0xe7, 0xf6, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xab, 0x74, 0x7a, 0x5d, 0x2a, 0x01,
	0x00, 0x00,
}
